name: Docker Image CI

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: ""
          major_pattern: "major:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker Image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build \
            -t jcamargo1951/docker-graphql:$NEW_VERSION \
            -t jcamargo1951/docker-graphql:latest .

      - name: Push Docker Images
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push jcamargo1951/docker-graphql:$NEW_VERSION
          docker push jcamargo1951/docker-graphql:latest

      - name: Create Git Tag
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
